---
- hosts: localhost
  become: yes
  vars:
    ansible_python_interpreter: '/bin/python3'
  

  tasks:
    - name: Create Mysql Secret
      community.kubernetes.k8s:
        state: "{{ action }}"
        definition:
          kind: Secret
          apiVersion: v1
          metadata:
            name: mysql-pass
            namespace: default
          data:
            password: d2VsY29tZQ==
          type: Opaque
    - name: Deploy MySQL storageClass
      community.kubernetes.k8s:
        state: "{{ action }}"
        definition:
          kind: StorageClass
          apiVersion: storage.k8s.io/v1
          metadata:
            name: staging
          provisioner: kubernetes.io/aws-ebs
          parameters:
            type: gp2
            fsType: ext4
    - name: Deploy PVC
      community.kubernetes.k8s:
        state: "{{ action }}"
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            namespace: default
            name: mysql-pv-claim
            labels:
              app: mysql
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
            storageClassName: staging
    - name: Deploy MySQL service
      community.kubernetes.k8s:
        state: "{{ action }}"
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            namespace: default
            name: python-mysql
            labels:
              app: mysql
          spec:
            ports:
              - port: 3306
            selector:
              app: mysql
            clusterIP: None
    - name: Deploy MySQL app
      community.kubernetes.k8s:
        state: "{{ action }}"
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            namespace: default
            name: python-mysql
            labels:
              app: mysql
          spec:
            selector:
              matchLabels:
                app: mysql
            strategy:
              type: Recreate
            template:
              metadata:
                labels:
                  app: mysql
              spec:
                containers:
                - image: mysql:5.6
                  name: mysql
                  env:
                  - name: MYSQL_ROOT_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: mysql-pass
                        key: password
                  ports:
                  - containerPort: 3306
                    name: mysql
                  volumeMounts:
                  - name: mysql-persistent-storage
                    mountPath: /var/lib/mysql
                volumes:
                - name: mysql-persistent-storage
                  persistentVolumeClaim:
                    claimName: mysql-pv-claim
    - name: Deploy python-login service
      community.kubernetes.k8s:
        state: "{{ action }}"
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            namespace: default
            name: helloapp-svc
            labels:
                app: helloapp
          spec:
            selector:
              app: helloapp
              version: green
            type: LoadBalancer
            ports:
              - protocol: TCP
                port: 80
                targetPort: 4000
    - name: Deploy Python app.
      community.kubernetes.k8s:
        state: "{{ action }}"
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            namespace: default
            name: hello-app
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: helloapp
                version: green
            template:
              metadata:
                name: helloapp-pod
                labels:
                  app: helloapp
                  version: green
              spec:
                containers:
                - name: helloapp-container
                  env:
                  - name: MYSQL_HOST
                    value: python-mysql
                  - name: MYSQL_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: mysql-pass
                        key: password
                  - name: MYSQL_USER
                    value: root
                  - name: MYSQL_DB
                    value: mysql
                  image: niranjankolli/eks-demo-lab:latest
                  imagePullPolicy: Always
                  ports:
                    - containerPort: 4000
